import os
import tkinter as tk
from tkinter import ttk

class TheCheck:
    @staticmethod
    def validate_numeric_input(new_value):
        return new_value == "" or (new_value.replace(".", "", 1).isdigit() and '.' not in new_value and float(new_value) >= 0)

LILAC = "#C8A2C8"

def setup_lilac_styles():
    style = ttk.Style()
    try:
        style.theme_use("clam")
    except tk.TclError:
        pass
    style.configure("Lilac.TFrame",  background=LILAC)
    style.configure("Lilac.TLabel",  background=LILAC, foreground="black", padding=0)
    style.map("Lilac.TLabel", background=[("active", LILAC)])
    
TOOLS_DIR = os.path.dirname(__file__)

ROOT_DIR = os.path.dirname(TOOLS_DIR)
DW2_BIN = os.path.join(ROOT_DIR, "DW2.bin")
ICON_DIR = os.path.join(TOOLS_DIR, "Icon_Files")
BACKUP_DIR = os.path.join(TOOLS_DIR, "Backups_For_Mod_Disabling")
MAPS_DIR = os.path.join(TOOLS_DIR, "maps")
MODS_DIR = os.path.join(TOOLS_DIR, "DW2_Mods")

HOSTFS_ELF = os.path.join(ROOT_DIR, "SLUS_200.79.hostfs.elf")

LINKDATA_DIR = os.path.join(ROOT_DIR, "unpacked_linkdata")

STAGE_DIRS = [
    os.path.join(LINKDATA_DIR, "AL_KOUK"),  # Yellow Turban Rebellion
    os.path.join(LINKDATA_DIR, "AL_KORO"),  # Hu Lao Gate
    os.path.join(LINKDATA_DIR, "AL_KANT"),  # Guan Du
    os.path.join(LINKDATA_DIR, "AL_CHOU"),  # Chang Ban
    os.path.join(LINKDATA_DIR, "AL_SEKI"),  # Chi Bi
    os.path.join(LINKDATA_DIR, "AL_GAPP"),  # He Fei
    os.path.join(LINKDATA_DIR, "AL_IRYO"),  # Yi Ling
    os.path.join(LINKDATA_DIR, "AL_GOJO"),  # Wu Zhang Plains
]

BACKGROUNDS_DIR = os.path.join(TOOLS_DIR, "backgrounds")
itemsoffset = 0x171648
unit_data = [0x142E90, 0x143003]
unit_names = [
    "0: Zhao Yun",
    "1: Guan Yu",
    "2: Zhang Fei",
    "3: Xiahou Dun",
    "4: Dian Wei",
    "5: Xu Zhu",
    "6: Zhou Yu",
    "7: Lu Xun",
    "8: Taishi Ci",
    "9: Diao Chan",
    "10: Zhuge Liang",
    "11: Cao Cao",
    "12: Lu Bu",
    "13: Sun Shang Xiang",
    "14: Liu Bei",
    "15: Sun Jian",
    "16: Sun Quan",
    "17: Dong Zhuo",
    "18: Yuan Shao",
    "19: Ma Chao",
    "20: Huang Zhong",
    "21: Xiahou Yuan",
    "22: Zhang Liao",
    "23: Sima Yi",
    "24: Lu Meng",
    "25: Gan Ning",
    "26: Jiang Wei",
    "27: Zhang Jiao",
    "28: Cao Ren",
    "29: Cheng Pu",
    "30: Huang Gai",
    "31: Han Dang",
    "32: Zhang Bao",
    "33: Zhang Liang",
    "34: Zhang Man Cheng",
    "35: Bo Zhang",
    "36: Cao Hong",
    "37: Yan Liang",
    "38: Wen Chou",
    "39: Zhang He",
    "40: Gongsun Zan",
    "41: Hua Xiong",
    "42: Xu Rong",
    "43: Gao Shun",
    "44: Li Ru",
    "45: Li Jue",
    "46: Jia Xu",
    "47: Guo Si",
    "48: Hu Zhen",
    "49: Xu Huang",
    "50: Yu Jin",
    "51: Chun Yuqiong",
    "52: Yue Jin",
    "53: Li Dian",
    "54: Xiahou En",
    "55: Cheng Yu",
    "56: Xun You",
    "57: Zhou Tai",
    "58: Ling Tong",
    "59: Xu Sheng",
    "60: Ding Feng",
    "61: Pang De",
    "62: Huang Quan",
    "63: Guan Xing",
    "64: Zhang Bao",
    "65: Shamoke",
    "66: Deng Ai",
    "67: Zhong Hui",
    "68: Wei Yan",
    "69: Ma Dai",
    "70: Guan Suo",
    "71: Yuan Tan",
    "72: Yuan Xi",
    "73: Yuan Shang",
    "74: Ju Shou",
    "75: Gao Lan",
    "76: Zhao Cen",
    "77: Niou Fu",
    "78: Fan Chou",
    "79: Wang Fang",
    "80: Li Meng",
    "81: He Jin",
    "82: Zhu Yun",
    "83: Lu Zhi",
    "84: Huangfu Song",
    "85: Zhang Chao",
    "86: Liu Yan",
    "87: Zou Ying",
    "88: Cheng Yuanzhi",
    "89: Deng Mao",
    "90: Guan Hai",
    "91: Pei Yuan Shao",
    "92: He Yi",
    "93: Yan Zheng",
    "94: Gao Sheng",
    "95: Liu Yan",
    "96: Song Xian",
    "97: Wei Xu",
    "98: Dong Xi",
    "99: Lu Wei Kuang",
    "100: Xun Chen",
    "101: Han Meng",
    "102: Han Xun",
    "103: Zhou Cang",
    "104: Guan Ping",
    "105: Sun Qian",
    "106: Mi Zhu",
    "107: Mi Fang",
    "108: Liu Feng",
    "109: Chen Dao",
    "110: Liao Hua",
    "111: Liu Qi",
    "112: Cao Pi",
    "113: Cao Zhang",
    "114: Zhu Huan",
    "115: Zhu Ran",
    "116: Jiang Qin",
    "117: Dong Xi",
    "118: Pan Zhang",
    "119: Yan Yan",
    "120: Wu Lan",
    "121: Lei Tong",
    "122: Zhang Ji",
    "123: Zhu Ran",
    "124: Jiang Qin",
    "125: Dong Xi",
    "126: Pan Zhang",
    "127: Yan Yan",
    "128: Private (Wei - sword)",
    "129: Corporal(Sergeant) (Wei - sword)",
    "130: Sergeant(Major) (Wei - sword)",
    "131: Private (Wei - spear)",
    "132: Sergeant (Wei - spear)",
    "133: Major (Wei - spear)",
    "134: Corporal(Private) (Wei - pike)",
    "135: Sergeant (Wei - pike)",
    "136: Major (Wei - pike)",
    "137: Guard (Wei - sword)",
    "138: Guard Captain (Wei - sword)",
    "139: Guard (Wei - spear)",
    "140: Guard Captain (Wei - spear)",
    "141: Guard (Wei - pike)",
    "142: Guard Captain (Wei - pike)",
    "143: Bowman (Wei)",
    "144: First bow (Wei)",
    "145: Crossbow (Wei)",
    "146: First Crossbow (Wei)",
    "147: Gate Guard (Wei)",
    "148: Gate Captain (Wei)",
    "149: Private (Wu - sword)",
    "150: Sergeant (Wu - sword)",
    "151: Major (Wu - sword)",
    "152: Private (Wu - spear)",
    "153: Sergeant (Wu - spear)",
    "154: Major (Wu - spear)",
    "155: Private (Wu - pike)",
    "156: Sergeant (Wu - pike)",
    "157: Major (Wu - pike)",
    "158: Guard (Wu - sword)",
    "159: Guard Captain (Wu - sword)",
    "160: Guard (Wu - spear)",
    "161: Guard Captain (Wu - spear)",
    "162: Guard (Wu - pike)",
    "163: Guard Captain (Wu - pike)",
    "164: Bowman (Wu)",
    "165: First Bow (Wu)",
    "166: Crossbow (Wu)",
    "167: F.Crossbow (Wu)",
    "168: Gate guard (Wu)",
    "169: Gate Captain (Wu)",
    "170: Private (Shu - sword)",
    "171: Sergeant (Shu - sword)",
    "172: Major (Shu - sword)",
    "173: Private (Shu - spear)",
    "174: Sergeant (Shu - spear)",
    "175: Major (Shu - spear)",
    "176: Private (Shu - pike)",
    "177: Sergeant (Shu - pike)",
    "178: Major (Shu - pike)",
    "179: Guard (Shu - sword)",
    "180: Guard Captain (Shu - sword)",
    "181: Guard (Shu - spear)",
    "182: G.Captain (Shu - spear)",
    "183: Guard (Shu - pike)",
    "184: G.Captain (Shu - pike)",
    "185: Bowman (Shu)",
    "186: First Bow (Shu)",
    "187: Crossbow (Shu)",
    "188: First Crossbow (Shu)",
    "189: G.guard (Shu)",
    "190: Gate Captain (Shu)",
    "191: Private (YS - sword)",
    "192: Sergeant (YS - sword)",
    "193: Major (YS - sword)",
    "194: Private (YS - spear)",
    "195: Sergeant (YS - spear)",
    "196: Major (YS - spear)?",
    "197: Private (YS - pike)?",
    "198: Sergeant (YS - pike)?",
    "199: Major (YS - pike)?",
    "200: Guard (YS - sword)",
    "201: G.Captain (YS - sword)",
    "202: Guard (YS - spear)",
    "203: G.Captain (YS - spear)",
    "204: Guard (YS - pike)",
    "205: G.Captain (YS - pike)",
    "206: Bowman (YS)",
    "207: First Bow (YS)",
    "208: Crossbow (YS)",
    "209: Catapult Chief (YS)",
    "210: Gate Guard (YS)",
    "211: G.Captain (YS)",
    "212: Private (Purple - sword)",
    "213: Sergeant (Purple - sword)?",
    "214: Major (Purple - sword)?",
    "215: Private (Purple - spear)?",
    "216: Sergeant (Purple - spear)?",
    "217: Major (Purple - spear)?",
    "218: Private (Purple - pike)?",
    "219: Sergeant (Purple - pike)?",
    "220: Major (Purple - pike)",
    "221: Guard (Purple - sword)",
    "222: G.captain (Purple - sword)",
    "223: Guard (Purple - spear)?",
    "224: G.Captain (Purple - spear)?",
    "225: Guard (Purple - pike)?",
    "226: G.Captain (Purple - pike)",
    "227: Bowman (Purple)",
    "228: First Bow (Purple)?",
    "229: Crossbow (Purple)?",
    "230: First Crossbow (Purple)",
    "231: Gate Guard (Purple)",
    "232: G.Captain (Purple)",
    "233: Trooper (YT - sword)",
    "234: Trooper (YT - spear)",
    "235: Trooper (YT - pike)",
    "236: Captain (YT - sword)",
    "237: Captain (YT - spear)",
    "238: Captain (YT - pike)",
    "239: General (YT - sword)",
    "240: General (YT - spear)",
    "241: General (YT - pike)",
    "242: Bowman (YT)",
    "243: First bow (YT)",
    "244: Bowman (YT)",
    "245: First Bow (YT)",
    "246: Gate guard (YT)",
    "247: Gate Captain (YT)",
    "248: Lady Guard",
    "249: Lady Guard",
    "250: Lady Guard",
    "251: Lady Captain",
    "252: Lady Bowman",
    "253: First Lady Bow",
    "254: Bodyguard",
]

unit_slot_names = [
    "Zhao Yun",
    "Guan Yu",
    "Zhang Fei",
    "Xiahou Dun",
    "Dian Wei",
    "Xu Zhu",
    "Zhou Yu",
    "Lu Xun",
    "Taishi Ci",
    "Diao Chan",
    "Zhuge Liang",
    "Cao Cao",
    "Lu Bu",
    "Sun Shang Xiang",
    "Liu Bei",
    "Sun Jian",
    "Sun Quan",
    "Dong Zhuo",
    "Yuan Shao",
    "Ma Chao",
    "Huang Zhong",
    "Xiahou Yuan",
    "Zhang Liao",
    "Sima Yi",
    "Lu Meng",
    "Gan Ning",
    "Jiang Wei",
    "Zhang Jiao",
    "Cao Ren",
    "Cheng Pu",
    "Huang Gai",
    "Han Dang",
    "Zhang Bao",
    "Zhang Liang",
    "Zhang Man Cheng",
    "Bo Zhang",
    "Cao Hong",
    "Yan Liang",
    "Wen Chou",
    "Zhang He",
    "Gongsun Zan",
    "Hua Xiong",
    "Xu Rong",
    "Gao Shun",
    "Li Ru",
    "Li Jue",
    "Jia Xu",
    "Guo Si",
    "Hu Zhen",
    "Xu Huang",
    "Yu Jin",
    "Chun Yuqiong",
    "Yue Jin",
    "Li Dian",
    "Xiahou En",
    "Cheng Yu",
    "Xun You",
    "Zhou Tai",
    "Ling Tong",
    "Xu Sheng",
    "Ding Feng",
    "Pang De",
    "Huang Quan",
    "Guan Xing",
    "Zhang Bao",
    "Shamoke",
    "Deng Ai",
    "Zhong Hui",
    "Wei Yan",
    "Ma Dai",
    "Guan Suo",
    "Yuan Tan",
    "Yuan Xi",
    "Yuan Shang",
    "Ju Shou",
    "Gao Lan",
    "Zhao Cen",
    "Niou Fu",
    "Fan Chou",
    "Wang Fang",
    "Li Meng",
    "He Jin",
    "Zhu Yun",
    "Lu Zhi",
    "Huangfu Song",
    "Zhang Chao",
    "Liu Yan",
    "Zou Ying",
    "Cheng Yuanzhi",
    "Deng Mao",
    "Guan Hai",
    "Pei Yuan Shao",
    "He Yi",
    "Yan Zheng",
    "Gao Sheng",
    "Liu Yan",
    "Song Xian",
    "Wei Xu",
    "Shi Huan",
    "Lu Wei Kuang",
    "Xun Chen",
    "Han Meng",
    "Han Xun",
    "Zhou Cang",
    "Guan Ping",
    "Sun Qian",
    "Mi Zhu",
    "Mi Fang",
    "Liu Feng",
    "Chen Dao",
    "Liao Hua",
    "Liu Qi",
    "Cao Pi",
    "Cao Zhang",
    "Zhu Huan",
    "Zhu Ran",
    "Jiang Qin",
    "Dong Xi",
    "Pan Zhang",
    "Yan Yan",
    "Wu Lan",
    "Lei Tong",
    "Zhang Ji",
    "Zhu Ran",
    "Jiang Qin",
    "Dong Xi",
    "Pan Zhang",
    "Yan Yan",
    "Private (Wei - sword)",
    "Corporal(Sergeant) (Wei - sword)",
    "Sergeant(Major) (Wei - sword)",
    "Private (Wei - spear)",
    "Sergeant (Wei - spear)",
    "Major (Wei - spear)",
    "Corporal(Private) (Wei - pike)",
    "Sergeant (Wei - pike)",
    "Major (Wei - pike)",
    "Guard (Wei - sword)",
    "Guard Captain (Wei - sword)",
    "Guard (Wei - spear)",
    "Guard Captain (Wei - spear)",
    "Guard (Wei - pike)",
    "Guard Captain (Wei - pike)",
    "Bowman (Wei)",
    "First bow (Wei)",
    "Crossbow (Wei)",
    "First Crossbow (Wei)",
    "Gate Guard (Wei)",
    "Gate Captain (Wei)",
    "Private (Wu - sword)",
    "Sergeant (Wu - sword)",
    "Major (Wu - sword)",
    "Private (Wu - spear)",
    "Sergeant (Wu - spear)",
    "Major (Wu - spear)",
    "Private (Wu - pike)",
    "Sergeant (Wu - pike)",
    "Major (Wu - pike)",
    "Guard (Wu - sword)",
    "Guard Captain (Wu - sword)",
    "Guard (Wu - spear)",
    "Guard Captain (Wu - spear)",
    "Guard (Wu - pike)",
    "Guard Captain (Wu - pike)",
    "Bowman (Wu)",
    "First Bow (Wu)",
    "Crossbow (Wu)",
    "F.Crossbow (Wu)",
    "Gate guard (Wu)",
    "Gate Captain (Wu)",
    "Private (Shu - sword)",
    "Sergeant (Shu - sword)",
    "Major (Shu - sword)",
    "Private (Shu - spear)",
    "Sergeant (Shu - spear)",
    "Major (Shu - spear)",
    "Private (Shu - pike)",
    "Sergeant (Shu - pike)",
    "Major (Shu - pike)",
    "Guard (Shu - sword)",
    "Guard Captain (Shu - sword)",
    "Guard (Shu - spear)",
    "G.Captain (Shu - spear)",
    "Guard (Shu - pike)",
    "G.Captain (Shu - pike)",
    "Bowman (Shu)",
    "First Bow (Shu)",
    "Crossbow (Shu)",
    "First Crossbow (Shu)",
    "G.guard (Shu)",
    "Gate Captain (Shu)",
    "Private (YS - sword)",
    "Sergeant (YS - sword)",
    "Major (YS - sword)",
    "Private (YS - spear)",
    "Sergeant (YS - spear)",
    "Major (YS - spear)?",
    "Private (YS - pike)?",
    "Sergeant (YS - pike)?",
    "Major (YS - pike)?",
    "Guard (YS - sword)",
    "G.Captain (YS - sword)",
    "Guard (YS - spear)",
    "G.Captain (YS - spear)",
    "Guard (YS - pike)",
    "G.Captain (YS - pike)",
    "Bowman (YS)",
    "First Bow (YS)",
    "Crossbow (YS)",
    "Catapult Chief (YS)",
    "Gate Guard (YS)",
    "G.Captain (YS)",
    "Private (Purple - sword)",
    "Sergeant (Purple - sword)?",
    "Major (Purple - sword)?",
    "Private (Purple - spear)?",
    "Sergeant (Purple - spear)?",
    "Major (Purple - spear)?",
    "Private (Purple - pike)?",
    "Sergeant (Purple - pike)?",
    "Major (Purple - pike)",
    "Guard (Purple - sword)",
    "G.captain (Purple - sword)",
    "Guard (Purple - spear)?",
    "G.Captain (Purple - spear)?",
    "Guard (Purple - pike)?",
    "G.Captain (Purple - pike)",
    "Bowman (Purple)",
    "First Bow (Purple)?",
    "Crossbow (Purple)?",
    "First Crossbow (Purple)",
    "Gate Guard (Purple)",
    "G.Captain (Purple)",
    "Trooper (YT - sword)",
    "Trooper (YT - spear)",
    "Trooper (YT - pike)",
    "Captain (YT - sword)",
    "Captain (YT - spear)",
    "Captain (YT - pike)",
    "General (YT - sword)",
    "General (YT - spear)",
    "General (YT - pike)",
    "Bowman (YT)",
    "First bow (YT)",
    "Bowman (YT)",
    "First Bow (YT)",
    "Gate guard (YT)",
    "Gate Captain (YT)",
    "Lady Guard",
    "Lady Guard",
    "Lady Guard",
    "Lady Captain",
    "Lady Bowman",
    "First Lady Bow",
    "Bodyguard (but doesnt seem to work)",
]
stage_data = [
    [0x24DD6DD8, 0x24DD7708, 0x24DD8038, 0x24DD8968, 0x24DD9298, 0x24DD9BC8, 0x24DDA4F8, 0x24DDAE28],
    [0x24DDF7A8, 0x24DE00D8, 0x24DE0A08, 0x24DE1338, 0x24DE1C68, 0x24DE2598, 0x24DE2EC8, 0x24DE37F8],
    [0x24DE8178, 0x24DE8AA8, 0x24DE93D8, 0x24DE9D08, 0x24DEA638, 0x24DEAF68, 0x24DEB898, 0x24DEC1C8],
    [0x24DF0B48, 0x24DF1478, 0x24DF1DA8, 0x24DF26D8, 0x24DF3008, 0x24DF3938, 0x24DF4268, 0x24DF4B98],
    [0x24DF9518, 0x24DF9E48, 0x24DFA778, 0x24DFB0A8, 0x24DFB9D8, 0x24DFC308, 0x24DFCC38, 0x24DFD568],
    [0x24E01EE8, 0x24E02818, 0x24E03148, 0x24E03A78, 0x24E043A8, 0x24E04CD8, 0x24E05608, 0x24E05F38],
    [0x24E0A8B8, 0x24E0B1E8, 0x24E0BB18, 0x24E0C448, 0x24E0CD78, 0x24E0D6A8, 0x24E0DFD8, 0x24E0E908],
    [0x24E13288, 0x24E13BB8, 0x24E144E8, 0x24E14E18, 0x24E15748, 0x24E16078, 0x24E169A8, 0x24E172D8]
    ]
